### ISSUE TITLE
Flexbox support

### ISSUE THREAD

**Issue by brunowego** [smallmultiples/grunt-screenshot-element#14]
I get issues with my project using flexbox. I read about the new version of phantomjs that supports flexbox in version 2, you have plans to update for this version? Thanks!

**Comment by Calvein** [comment]
Unfortunately we don't use this anymore so it's most unlikely that we will fix this, but feel free to add a PR or to fork the repo if needed.

**Comment by brunowego** [comment]
I'll try to work on it, good opportunity to improve my skills! :+1:
